import React from 'react';
import Card from '../components/ui/Card';
import Button from '../components/ui/Button';

export default function Reports() {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="container" style={{ paddingTop: '32px', paddingBottom: '64px' }}>
      <div className="flex-between mb-xl">
        <h1 className="h1-text">Sustainability Report</h1>
        <Button variant="primary" onClick={handlePrint}>Download PDF</Button>
      </div>

      <Card className="p-xl" id="report-content">
        <div className="text-center mb-xl">
          <h1 className="hero-text text-primary">GreenPrint</h1>
          <h2 className="h2-text text-secondary">Executive Summary - Q2 2026</h2>
        </div>

        <div className="grid-12 mb-lg">
          <div style={{ gridColumn: 'span 6' }}>
            <h3 className="h3-text mb-md">Carbon Score</h3>
            <div className="hero-text text-primary mb-sm">78 / 100</div>
            <p className="body text-secondary">You are performing better than 85% of users in your demographic.</p>
          </div>
          <div style={{ gridColumn: 'span 6' }}>
            <h3 className="h3-text mb-md">Monthly Footprint</h3>
            <div className="hero-text text-primary mb-sm">450 kg CO2e</div>
            <p className="body text-secondary">A 15% reduction since last quarter. Your highest emission category is Energy.</p>
          </div>
        </div>

        <h3 className="h3-text mb-md mt-xl">Key Recommendations</h3>
        <ul className="body text-secondary" style={{ marginLeft: '24px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
          <li>Switch to a 100% renewable energy provider.</li>
          <li>Substitute 2 car trips per week with biking or public transit.</li>
          <li>Implement "Meatless Mondays" to reduce dietary footprint.</li>
        </ul>

        <h3 className="h3-text mb-md mt-xl">Achievements</h3>
        <p className="body text-secondary">
          Unlocked: First Step, Energy Saver.<br/>
          Next goal: Plant Based (requires 1 week of vegetarian diet).
        </p>

        <div className="mt-xl text-center">
          <p className="caption text-secondary">Generated by GreenPrint AI Personal Sustainability Coach</p>
        </div>
      </Card>
    </div>
  );
}
